environment:
  obstacles:
    obs_197:
      corners:
      - [0.7075436024800257, 0.12643462934726316]
      - [0.7467952152360771, 0.12643462934726316]
      - [0.7467952152360771, 0.16568624210331448]
      - [0.7075436024800257, 0.16568624210331448]
      shape: polygon
    obs_311:
      corners:
      - [0.4540663982283009, 0.5125973806242542]
      - [0.5381247879546228, 0.5125973806242542]
      - [0.5381247879546228, 0.596655770350576]
      - [0.4540663982283009, 0.596655770350576]
      shape: polygon
    obs_42:
      corners:
      - [0.0678289750132992, 0.3774362135918825]
      - [0.09476555723337367, 0.3774362135918825]
      - [0.09476555723337367, 0.40437279581195695]
      - [0.0678289750132992, 0.40437279581195695]
      shape: polygon
    obs_65:
      corners:
      - [0.6124739717574137, 0.4103455632637554]
      - [0.6478530404747085, 0.4103455632637554]
      - [0.6478530404747085, 0.44572463198105017]
      - [0.6124739717574137, 0.44572463198105017]
      shape: polygon
    obs_728:
      corners:
      - [0.6386076602859645, 0.5995473413121668]
      - [0.6802964726222145, 0.5995473413121668]
      - [0.6802964726222145, 0.6412361536484168]
      - [0.6386076602859645, 0.6412361536484168]
      shape: polygon
