chance_constraint: 0.3
cleanDist: 0.1
cleanMap: false
coVarX: 0.0001
coVarY: 0.0001
end_location: [1, 1, 0, 0]
environment: ./config/map.yaml
horizon_cost_proportion: 0.99
horizon_polygon_size: 50
margin: 0.1
max_control: 0.98
max_velocity: 0.06
outFolder: '[./output/]'
receding_horizon: true
start_location: [0.0, 0.0, 0, 0]
waypoints: 4
waypoints_val: 7.0
